config/routes.rb
Rails.application.routes.draw do
  get 'archives/index'
  resources :entries
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :meal_type, :calories, :protiens, :carbohydrates, :fats, presence: true

  def day
    self.created_at.strftime("%b %e, %Y")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.where("created_at > ?", Date.today)
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy!

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :protiens, :carbohydrates, :fats)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-half">
    <% @entries.each do |day,entries| %>
      <h3 class="is-size-3 has-weight-bold mb-4 has-text-centered">Entries of <%= day %></h3>

      <nav class="level is-mobile">
        <div class="level-item has-text-centered">
            <div>
              <p class="heading">Calories</p>
              <p class="title"><%= entries.pluck(:calories).sum %></p>
            </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Protiens</p>
            <p class="title"><%= entries.pluck(:protiens).sum %>g</p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Carbohydrates</p>
            <p class="title"><%= entries.pluck(:carbohydrates).sum %>g</p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Fats</p>
            <p class="title"><%= entries.pluck(:fats).sum %>g</p>
          </div>
        </div>
      </nav>

      <% entries.each do |entry| %>
        <%= link_to entry_path(entry) do %>
          <div class="card">
            <div class="card-content">
              <strong><%= entry.meal_type %></strong><br/>
              <%= entry.calories %> calories,
              <%= entry.protiens %>g protiens,
              <%= entry.carbohydrates %>g carbs,
              <%= entry.fats %> fats
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>">
  <p>
    <strong>Meal type:</strong>
    <%= entry.meal_type %>
  </p>

  <p>
    <strong>Calories:</strong>
    <%= entry.calories %>
  </p>

  <p>
    <strong>Protiens:</strong>
    <%= entry.protiens %>
  </p>

  <p>
    <strong>Carbohydrates:</strong>
    <%= entry.carbohydrates %>
  </p>

  <p>
    <strong>Fats:</strong>
    <%= entry.fats %>
  </p>

</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meal_type, class: "label" %>
    <%= form.text_field :meal_type, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :calories, class: "label" %>
    <%= form.number_field :calories, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :protiens, class: "label" %>
    <%= form.number_field :protiens, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :carbohydrates, class: "label" %>
    <%= form.number_field :carbohydrates, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :fats, class: "label" %>
    <%= form.number_field :fats, class: "input" %>
  </div>

  <div class="action">
    <%= form.submit class:"button is-link"%>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3">Editing entry</h1>
    <%= render "form", entry: @entry %>
  </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  foodlog &ndash; <%= DateTime.now.to_fs(:nice_date) %>
<% end %>

<div class="columns mt-6 is-centered">
  <% @entries.each do |entry| %>
  <div class="column is-one-quarter">
    <div class="card">
      <header class="card-header">
        <p class="card-header-title"><%= entry.meal_type %></p>
      </header>

      <div class="card-content">
        <div class="content">
          <p><span class="has-text-weight-bold"><%= entry.calories %></span> calories</p>
          <p><span class="has-text-weight-bold"><%= entry.protiens %></span> gm of protiens</p>
          <p><span class="has-text-weight-bold"><%= entry.carbohydrates %></span> gm of carbohydrates</p>
          <p><span class="has-text-weight-bold"><%= entry.fats %></span> gm of fats</p>
          <p class="italic"> <%= time_ago_in_words(entry.created_at) %> ago</p>
        </div>
      </div>

      <div class="card-footer">
        <%= link_to "show", entry, class: "card-footer-item"%>
        <%= link_to "edit", edit_entry_path(entry), class: "card-footer-item" %>
        <%= link_to "delete", entry, method: :delete, class: "card-footer-item" %>
      </div>

    </div>
  </div>

<% end %>
</div>

<div class="columns is-centered mt-6">
  <%= link_to "Show all", archives_index_path, class: "button is-centered is-link" %>
</div>

app/views/entries/new.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3">New entry</h1>
    <%= render "form", entry: @entry %>
  </div>
</div>

<div>
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/entries/show.html.erb
<% content_for :title do %>
  <%= DateTime.now.to_fs(:nice_date) %> &ndash; <%= @entry.meal_type %>
<% end %>

<div class="columns mt-6 is-centered">
  <div class="column is-one-third">

    <nav class="panel is-warning">
      <p class="panel-heading">
        <%= @entry.meal_type %>
      </p>
      <div class="panel-block">
        calories: <%= @entry.calories %>
      </div>
      <div class="panel-block">
        protiens: <%= @entry.protiens %>
      </div>
      <div class="panel-block">
        carbs: <%= @entry.carbohydrates %>
      </div>
      <div class="panel-block">
        fats: <%= @entry.fats %>
      </div>
    </nav>

    <div class="columns is-mobile">
      <div class="column">
        <%= link_to "edit", edit_entry_path(@entry), class: "button is-gray" %>
        <%= link_to "back", entries_path, class: "button is-gray" %>
        <%= button_to "delete", @entry, method: :delete, class: "button is-gray" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.1/css/bulma.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "shared/header" %>
    <% if notice.present? %>
      <div class="notification is-warning is-light"><%= notice %></div>
    <% end %>
    <% if alert.present? %>
      <div class="notification is-danger is-light"><%= alert %></div>
    <% end %>

    <div class="container">
        <%= yield %>
    </div>

  </body>
</html>